### PR TITLE
Adding syncronization TW(annotation) - Trello(description)

### PR DESCRIPTION
**Pull request by leikoilja**
This PR addresses issue https://github.com/ogarcia/trellowarrior/issues/25.

Adding synchronization between TaskWarrior task's annotations and Trello task's description.
Note, since annotations are a list in TW they are simply concated into a string separated by a new line `\n`.
Note, since annotation are a list in TW when Trello updates TW it will overwrite (delete all old annotations).

### CODE REVIEW

**Comment by ogarcia** [comment]
Is a great idea, but I need do some tests before merging :-)

**Comment by leikoilja** [comment]
Ofc, @ogarcia. Let me know if I can help anyhow

**Comment by leikoilja** [comment]
@ogarcia, have you had a chance to test it?

**Comment by ogarcia** [comment]
@leikoilja I've finally had time to review this! I did a different implementation of this so I cannot merge this pull request, but may thanks for your ideas!

**Pull request closed without merging**
